### ISSUE TITLE
NTSC Genesis Model 1

### ISSUE THREAD

**Issue by FiZiX** [SukkoPera/MegaDrivePlusPlus#1]
Has this been tested on an NTSC Genesis Model 1? If not, should I provide pics of my board?

**Comment by SukkoPera** [comment]
I think someone tried it and had some issues. Unfortunately I don't have an NTSC console, so I can't test on my own. If you want to try and report your experience, it would be great.

Installation-wise, there should be no problem, I think you can easily spot all the needed solder points.

**Comment by FiZiX** [comment]
Thanks for your response. Unfortunately, my time is at a premium right now so I don't think I'll have time to test this for a while. If I do get time, I'll re-open the issue and report my results.

**Comment by SukkoPera** [comment]
Ok, thanks anyway.
