### ISSUE TITLE
Something wrong??

### ISSUE THREAD

**Issue by Epitaph78** [SukkoPera/MegaDrivePlusPlus#10]
Hi. I've installed this in my Mega Drive 2 with an Arduino Nano, verified all the connections were correct with a multimeter, but when I turn the console on, it seems to be locked in 60hz mode, the reset button does absolutely nothing at all, the START+DOWN combination changed the colour of the LED from green, to blue, to red, and back to green, and that's all it does. Even changing the mode and then turning the console off and on changes nothing. I find it weird the button combination is different to what it's supposed to be, and as I said, nothing at all changes on the screen. Would appreciate any insight.

**Comment by SukkoPera** [comment]
Did you close the ticket because you have already solved the issue?

**Comment by Epitaph78** [comment]
Yes. I was using a schematic from Sega-16 which showed the relation between
the colour coding and the arduino pinout, but it seems that pinout was an
old one as I later noticed the pinout in the sketch was different. So it
was a case of changing the wires around on the arduino, and it worked.

**Comment by SukkoPera** [comment]
This made me realize there's no official wiring diagram on the wiki. Reopening so that I remember to fix that.

**Comment by Epitaph78** [comment]
👍👍

**Comment by SukkoPera** [comment]
[Installation page](https://github.com/SukkoPera/MegaDrivePlusPlus/wiki/Installation) revamped, hopefulyl everything will be clearer now.
