### ISSUE TITLE
Mega Drive II MD++ Guide using Nano Board?

### ISSUE THREAD

**Issue by shanotype** [SukkoPera/MegaDrivePlusPlus#14]
Could someone please update the Mega Drive II instalation guide in the wiki with clear instructions using the Nano board? Dunno what goes where, cheers!

**Comment by SukkoPera** [comment]
I think that by reading [this[(https://github.com/SukkoPera/MegaDrivePlusPlus/wiki/Installation) and [this](https://github.com/SukkoPera/MegaDrivePlusPlus/wiki/Installation-on-Mega-Drive-2) you have all the info you need.

However, AssemblerGames forum user nextria has just contributed this image which can make things clearer:
![img](https://github.com/SukkoPera/MegaDrivePlusPlus/wiki/images/nextria.jpg)

**Comment by shanotype** [comment]
Thank you very much! :)
