### ISSUE TITLE
is teensy ++ 2.0 compatibile?

### ISSUE THREAD

**Issue by TurBoss** [SukkoPera/MegaDrivePlusPlus#17]
hello,

 does MegadrivePlusPlus require an arduino nano
it has some hardware requirements?

thanks

**Comment by SukkoPera** [comment]
Why use a $20 Teensy when a $2 Nano is more than enough? Besides the Teensy is a 3.3V device IIRC, so it can't be used out of the box (it might be 5V-tolerant but I don't really know).

**Comment by TurBoss** [comment]
oh i should specify more details :)
is a 5v clone

**Comment by SukkoPera** [comment]
I'm sorry but I don't know. I have never used Teensy boards.

**Comment by TurBoss** [comment]
does it require any interupts?
thats the only thing i thik could be needed if required

**Comment by SukkoPera** [comment]
Yes, it uses an interrupt which is triggered by changes in the SELECT signal (pin 7 of the controller port).

**Comment by TurBoss** [comment]
Thank you so much
