### ISSUE TITLE
My PAL MegaDrive 2 is not in the list (PC BD MD2 VA0 PAL)

### ISSUE THREAD

**Issue by lorecast162** [SukkoPera/MegaDrivePlusPlus#21]
Hello. My PAL Mega Drive 2 (PC BD MD2 VA0 PAL) is not in the list.

Sorry in advance if the pics aren't good enough but they're as good as I can take them right now.

![20201102_115944](https://user-images.githubusercontent.com/17319563/97861824-aaf21a80-1d04-11eb-8365-09dabda65189.jpg)
![20201102_115932](https://user-images.githubusercontent.com/17319563/97861825-acbbde00-1d04-11eb-82a6-1ceb54df2a64.jpg)

**Comment by lorecast162** [comment]
I suspect it to be similar to the VA1 but I'm not sure

**Comment by SukkoPera** [comment]
Yes, as far as I can say it looks exactly the same. Try and let me know.

**Comment by lorecast162** [comment]
I can't perform the mod yet, it's my only mega drive and unless I'm sure it's ok I'm not too inclined to doing it. Hope you understand.

**Comment by lorecast162** [comment]
Tbf, it's not much about not being _able_ to do it (I'm sorta confident enough in my skills) but more about not really _wanting_ to take the plunge and do it

**Comment by SukkoPera** [comment]
Sure, I understand, but I cannot help much, unless someone donates this board exactly.

Tagging as *help needed*.

**Comment by chulpanovich** [comment]
> Здравствуйте. Мой PAL Mega Drive 2 (ПК BD MD2 VA0 PAL) отсутствует в списке.
> 
> Заранее извиняюсь, если фотографии недостаточно хороши, но они настолько хороши, насколько я могу их сделать прямо сейчас.
> 
> ![20201102_115944](https://user-images.githubusercontent.com/17319563/97861824-aaf21a80-1d04-11eb-8365-09dabda65189.jpg)
> ![20201102_115932](https://user-images.githubusercontent.com/17319563/97861825-acbbde00-1d04-11eb-82a6-1ceb54df2a64.jpg)

This is how you can do it.
![install](https://user-images.githubusercontent.com/57206610/102357946-dfd2dc00-3fe9-11eb-95ad-74d0c227f47d.jpg)
![install2](https://user-images.githubusercontent.com/57206610/102357958-e2cdcc80-3fe9-11eb-9bb2-6c883a6b9a9a.jpg)

**Comment by SukkoPera** [comment]
Thanks a lot @chulpanovich! Much appreciated!

@lorecast162 IF you happen to try this out, let me know if it works so that I can add it to the official docs.

**Comment by pseiler** [comment]
I'll try this mod soon. But it'll take some time. I need to first flash the new/faster arduino bootloader etc. Also I take my time.
I will also add a picture of the finished mod.

**Comment by pseiler** [comment]
The tutorial defenitely also working for the VA0 console. I successfully modded my Mega Drive VA0 PAL.
The cable management is trahs thats why I have no proper pictures.

Only this for reference
https://circuit-board.de/forum/index.php/Attachment/182409-PXL-20220118-120130224-jpg/

But the modchip works as expected.
Had to adjust the LED values to use a duoLED.
Maybe just mention this is in the Wiki.

Thanks for having this awesome option to mod a megadrive.
Mine works flawlessly with a DFO to generate a proper 60Hz signal.

**Comment by SukkoPera** [comment]
Done, thanks a lot for your report!
