### ISSUE TITLE
PC BD MD2 VA1.8 JAP (NTSC Japan)

### ISSUE THREAD

**Issue by kinmami** [SukkoPera/MegaDrivePlusPlus#26]
Hello,
I have been working on a Japanese MD2 model.
It came without the power led but the rear panel has a hole that suits a 5mm Common-Cathode Red-Green LED for the purpose.
I have used 220-ohm resistors in series to each anode considering my Arduino is supplied by 4.8V.
The test points and arrangement are shown in the following attachments.

[SSL-LX5097IGW.pdf](https://github.com/SukkoPera/MegaDrivePlusPlus/files/8223406/SSL-LX5097IGW.pdf)

![WhatsApp Image 2022-03-10 at 21 27 36](https://user-images.githubusercontent.com/33851062/157663373-3a7bd57f-8102-4b78-a80d-b8e410faa250.jpeg)
![WhatsApp Image 2022-03-10 at 21 27 35 (1)](https://user-images.githubusercontent.com/33851062/157663383-d627a31b-bd7d-4528-a2bc-ac873cccfef9.jpeg)
![WhatsApp Image 2022-03-10 at 21 27 35 (2)](https://user-images.githubusercontent.com/33851062/157663385-8ec25dc6-818d-4b2c-a8f0-ece659cc882b.jpeg)
![WhatsApp Image 2022-03-10 at 21 27 35 (3)](https://user-images.githubusercontent.com/33851062/157663388-ac09f30f-7988-4bc3-b9f0-e806923ac1b1.jpeg)
![WhatsApp Image 2022-03-10 at 21 27 35 (4)](https://user-images.githubusercontent.com/33851062/157663391-2351ede7-2c21-4c75-90aa-fd47df8bc6f1.jpeg)
![WhatsApp Image 2022-03-10 at 21 27 35](https://user-images.githubusercontent.com/33851062/157663393-94d32de9-e6e3-40f5-a91f-fe00684d32c0.jpeg)
![WhatsApp Image 2022-03-10 at 21 27 36 (1)](https://user-images.githubusercontent.com/33851062/157663394-36e07533-9b00-45fb-bd9a-f74dc525e83e.jpeg)
![WhatsApp Image 2022-03-10 at 21 27 36 (2)](https://user-images.githubusercontent.com/33851062/157663396-f844b20d-32aa-458e-963b-a7502dc120e8.jpeg)
![WhatsApp Image 2022-03-10 at 21 27 36 (3)](https://user-images.githubusercontent.com/33851062/157663400-144f5458-cfc5-4b03-a30f-0ff475ab7172.jpeg)
![WhatsApp Image 2022-03-10 at 21 27 36 (4)](https://user-images.githubusercontent.com/33851062/157663404-67caaaab-2998-41d6-8909-189f0f0600d2.jpeg)
![WhatsApp Image 2022-03-10 at 21 27 36 (5)](https://user-images.githubusercontent.com/33851062/157663409-66daf916-7f0c-4d75-a792-8ed1033db3e8.jpeg)
![WhatsApp Image 2022-03-10 at 21 27 36 (6)](https://user-images.githubusercontent.com/33851062/157663411-dbbea3e8-0f00-41f1-8d6c-173191f92321.jpeg)

**Comment by SukkoPera** [comment]
Added link into Wiki, thanks a lot for your contribution!
