### ISSUE TITLE
Re-routing pad input.

### ISSUE THREAD

**Issue by DieSkaarj** [SukkoPera/MegaDrivePlusPlus#28]
Hi there,

I'm trying to figure out how to re-route the pad read pins so that they populate D8 to D2 consecutively with the SELECT line on INT1/D3. I can't seem to find how the pins are arranged in the code. Can someone point me in the right direction?

Thanks in advance,
David

**Comment by SukkoPera** [comment]
Why would you need to do that? There's a reason if pins were chosen the way they were.

**Comment by DieSkaarj** [comment]
I am using RX and TX to control the LED (when not debugging) because pins D10-13 are being used for the Overclock mod. So, moving the pad pins along will keep things tidier.

Here is the desired layout:

                                     +-----+
                        +------------| USB |------------+
                        |            +-----+            |
         Clock (AD9833) | [ ]D13/SCK        MISO/D12[X] | Pause (AD9833)
                        | [ ]3.3V           MOSI/D11[X]~| Data (AD9833)
                        | [ ]V.ref     ___    SS/D10[X]~| FSync (AD9833)
              Reset Out | [X]A0       / N \       D9[ ]~| 
               Reset In | [X]A1      /  A  \      D8[X] | Pad Port Pin 1
     JP3/4 (Video Mode) | [X]A2      \  N  /      D7[X] | Pad Port Pin 2
       JP1/2 (Language) | [X]A3       \_0_/       D6[X]~| Pad Port Pin 3
              [LCD SDA] | [X]A4/SDA               D5[X]~| Pad Port Pin 4
              [LCD SCL] | [X]A5/SCL               D4[X] | Pad Port Pin 6
                        | [ ]A6              INT1/D3[X]~| Pad Port Pin 7
                        | [ ]A7              INT0/D2[X] | Pad Port Pin 9
                        | [ ]5V                  GND[ ] |
                        | [ ]RST                 RST[ ] |
                        | [ ]GND   5V MOSI GND   TX1[X] | LED Color 1
                        | [ ]Vin   [X] [ ] [X]   RX0[X] | LED Color 2
                        |          [ ] [ ] [ ]          |
                        |         MISO SCK RST          |
                        | NANO-V3                       |
                        +-------------------------------+
                                   +5V     GND

**Comment by SukkoPera** [comment]
Well, it turns out that D8 is on a different port than D0-7, which would complicate and slow down (and probably make unreliable) the polling code. There's no point in compromising functionality for "tidier" reasons, as I see it. Why can't you use D8/9?

**Comment by DieSkaarj** [comment]
A', I understand now; I can. I see that was explained in the .ino file too.

It was purely for superficial reasons. Thank you for clearing that up.
